volumes:
  cloudflared-home:
    name: cloudflared-celesteria-net-home

networks:
  default-network:
    name: cloudflared-celesteria-net-network
  sentry-frontend:
    external: true

services:
  cloudflared-celesteria-net:
    build:
      context: ./cloudflared
      dockerfile: ./Dockerfile
    container_name: cloudflared-celesteria-net
    image: local-cloudflared-image
    init: true
    volumes:
      - cloudflared-home:/root
      - ./cloudflared/tunnel-config.yaml:/tmp/tunnel-config.yaml
    networks:
      - default-network
      - sentry-frontend
